### ISSUE TITLE
Api to generate ease the use of some double nested Enum

### ISSUE THREAD

**Issue by ThomAub** [davidB/vega_lite_3.rs#11]
Following the discussion in #10, if a string cannot be passed into the Enum directly it should be possible to have an APi that is easier to use by creating some `impl Into<Xxxx> for Xxxx::Enum`.
This is currently done for Mark: `Mark::Line` is possible thanks to the code [here](https://github.com/procyon-rs/vega_lite_3.rs/blob/master/src/lib.rs#L44). 

Should it be an impl for most common Types/Enum or create a macro ??

**Comment by mockersf** [comment]
It should be possible to implement `From` for all enum variants that are a tuple with only one field...

I think the easiest way to do it would be while generating the schema, keeping track of those variants and then implementing all the traits. But it's not very rusty...

The other way would be to derive it... I found the (very) old crate [enum_derive](https://crates.io/crates/enum_derive) which did it from before the time when we could write derive macro in rust...

**Comment by mockersf** [comment]
Oh, found [derive_more](https://crates.io/crates/derive_more) which is much more recent!

https://jeltef.github.io/derive_more/derive_more/from.html#enums
