### ISSUE TITLE
mention crate in Vega-Lite ecosystem

### ISSUE THREAD

**Issue by mockersf** [davidB/vega_lite_3.rs#16]
Once crate has reached good enough level, add it to https://vega.github.io/vega-lite/ecosystem.html

**Comment by brainstorm** [comment]
Precisely, I only found out about this crate via https://www.reddit.com/r/rust/comments/f8ero2/plotly_for_rust/

**Comment by ThomAub** [comment]
Should we : 
- mention vega_lite_3 (or vega_lie_4) now and then update when procyon will be more user friendly ? 
- advertise procyon right now with the disclaimer there is work in progress ?

**Comment by davidB** [comment]
I vote for 
> mention vega_lite_3 (or vega_lie_4) now and then update when procyon will be more user friendly

**Comment by ThomAub** [comment]
I will update the above PR when procyon is ready so closing this issue.
