### ISSUE TITLE
impossible to serialize null values

### ISSUE THREAD

**Issue by mockersf** [davidB/vega_lite_3.rs#5]
There are a few cases when a value present but with `null` value has a different behaviour than a missing value.
for example, setting an [axis](https://docs.rs/vega_lite_3/0.2.3/vega_lite_3/struct.XClass.html#structfield.axis) as `null` should remove the axis.

We should have three state for such fields instead of two (`Option`):
- no value, use default value
- null value
- value

**Comment by davidB** [comment]
Or for this field, we can translate None to null, and for default value suggest to the user to use Axis::default() explicitly instead of delegating defaulting to vega-lite engine. It looks less Javascript and more Rust api approach.

An other approach could be `Option<Option<Axis>>` with `None => undefined` and the `Some(None) => null`.  But it's add boilerplate for common use cases.

Every approach are not consistent with the other elements of the api or the mapping rules :-(

**Comment by LukeMathWalker** [comment]
Could an explicit enum do the trick?
E.g.
```rust
pub enum AxisParameter {
  Unspecified,
  Null,
  Value(Axis)
}
```

**Comment by mockersf** [comment]
In the son spec, the fields where `null` has a special meaning (77 of them, I think) are marked as:
```json
"anyOf": [
    {
        "$ref": "#/definitions/Axis"  // <- any type, not just Axis
    },
    {
        "type": "null"
    }
]
```
To detect those fields properly, we would have to change [quicktype](https://github.com/quicktype/quicktype) or rewrite something to generate rust bindings...

Or we can replace every `Option` with... `NullableOption`

```rust
use derive_builder::Builder;
use serde::{Serialize, Serializer};

#[derive(Clone, Debug)]
pub enum NullableOption<T: Clone> {
    None,
    Null,
    Some(T),
}
impl<T: Clone> NullableOption<T> {
    fn is_none(&self) -> bool {
        match self {
            NullableOption::None => true,
            _ => false,
        }
    }
}
impl<T: Clone> From<T> for NullableOption<T> {
    fn from(value: T) -> Self {
        NullableOption::Some(value)
    }
}
impl<T: Clone> Default for NullableOption<T> {
    fn default() -> Self {
        NullableOption::None
    }
}
impl<T> Serialize for NullableOption<T>
where
    T: Serialize + Clone,
{
    #[inline]
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        match *self {
            NullableOption::Some(ref value) => serializer.serialize_some(value),
            NullableOption::None => serializer.serialize_none(),
            NullableOption::Null => serializer.serialize_none(),
        }
    }
}

#[derive(Builder, Debug, Serialize)]
#[builder(setter(into))]
pub struct MyStruct {
    #[builder(default)]
    #[serde(skip_serializing_if = "NullableOption::is_none")]
    pub ino: NullableOption<i32>,
}

fn main() {
    println!(
        "{}",
        serde_json::to_string(&MyStructBuilder::default().ino(3).build().unwrap()).unwrap()
    );
    println!(
        "{}",
        serde_json::to_string(
            &MyStructBuilder::default()
                .ino(NullableOption::Null)
                .build()
                .unwrap()
        )
        .unwrap()
    );
    println!(
        "{}",
        serde_json::to_string(
            &MyStructBuilder::default()
                .ino(NullableOption::None)
                .build()
                .unwrap()
        )
        .unwrap()
    );
}
```
which gives:
```
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/nullable-option`
{"ino":3}
{"ino":null}
{}
```

but makes the doc even less easier to read...

**Comment by mockersf** [comment]
after talking with @davidB, I went with a three states option saying explicitly what it's doing:
```rust
pub enum RemovableValue<T: Clone> {
     Default,
     Remove,
     Specified(T),
 }
```

it should be transparent unless you want to remove the value, in which case you use `RemovableValue::Remove` as shown in example [diverging_stacked_bar_chart.rs](https://github.com/procyon-rs/vega_lite_3.rs/blob/master/examples/diverging_stacked_bar_chart.rs#L29)
